### ISSUE TITLE
Ability to add posts does not work

### ISSUE THREAD

**Issue by syedwshah** [syedshah94/meme_app#1]
Not sure why users cannot add new posts from their dashboard. There's no useful error message here either, so I'm not sure where I went wrong.
The files in question regarding this may be the following files on the React side:
Dashboard.jsx
AddPostForm.jsx

Basically in Dashboard.jsx (lines 37-53) is the addPost method for my Dashboard class, which would be sent as a prop to AddPostForm. 
Get requests on the site seem to work since the PostList class, which is the sort of "news feed" on the app, works. So I basically wrote the same code but for 'POST'.

**Comment by dominic-farquharson** [comment]
You had a typo in one of your headers. The content-type was set as `application.json` instead of `application/json` so your request body was never being sent.


```js
addPost(e, data) {
    fetch('/posts', {
      method: "POST",
      headers: {
        'Content-Type': 'application/json', // typo was here
        token: Auth.getToken(),
        'Authorization': `Token ${Auth.getToken()}`
      },
      body: JSON.stringify({
        post: data,
      }),
    }).then(res => res.json())
      .then(res => {
        console.log(res);
        this.getUserPosts();
      }).catch(err => console.log(err));
  }
```
