### ISSUE TITLE
React components not re-rendering

### ISSUE THREAD

**Issue by syedwshah** [syedshah94/meme_app#3]
On /dash route, I have my component Dashboard.jsx running. The issue now comes in to play when a user creates or edit's a new post; the Component doesn't re-render. This seems to work fine on delete action, but that's about it. Let me know if we can meet up and you can see this on my computer and just work through it with me a lot faster than on your local machine.

**Comment by dominic-farquharson** [comment]
This form is performing a `GET` request since you're never preventing the default action. That's why your state isn't persisting. 

```html
 <form onSubmit={(e) => this.props.addPost(e,this.state)} >
  <input type="text" name="title" placeholder="Title" value={this.state.title} onChange={this.handleChange} />
  <input type="text" name="description" placeholder="Description" value={this.state.description} onChange={this.handleChange} />
  <input type="text" name="url" placeholder="Image Url" value={this.state.url} onChange={this.handleChange} />
  <input type="submit" value="Create Post" />
</form>
```

You also need to bind your methods. An error is thrown after you make your POSt request since the methods are undefined.

```js
this.getUserPosts = this.getUserPosts.bind(this);
this.addPost = this.addPost.bind(this);
```

**Comment by syedwshah** [comment]
Thanks Dom, It worked!
